weapon_shop:
    resource: "@weaponShopBundle/Controller"
    type:   annotation

# src/weapon/ShopBundle/Resources/config/routing.yml
weapon_shop_homepage:
    path:     /hello/{name}
    defaults: { _controller: weaponShopBundle:Default:index }
