_weapon_shop:
    resource: "@weaponShopBundle/Resources/config/routing.yml"
    type:   annotation
    prefix:   /shopadmin

# src/weapon/ShopBundle/Resources/config/routing.yml
weapon_shop_homepage:
    path:     /hello/{name}
    defaults: { _controller: weaponShopBundle:Default:index }
