weapon_shop:
    resource: "@weaponShopBundle/Controller/"
    type:     annotation

   account_register:
        path:     /register
        defaults: { _controller: weaponShopBundle:Registration:register }
