weapon_shop:
    resource: "@weaponShopBundle/Controller/"
    type:     annotation

    account_register:
        path:     /register
        defaults: { _controller: AcmeAccountBundle:Account:register }

    account_create:
        path:     /register/create
        defaults: { _controller: AcmeAccountBundle:Account:create }